name: Solar System - Code coverage

on:
  workflow_dispatch:
  push:
    branches: [ "feature" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}     

  
jobs:
  unit-testing:

    strategy:
      matrix:
        nodejs-version: [18,20]
        os-type: [ubuntu-latest,macos-latest]
        exclude: 
          - os-type: macos-latest
            nodejs-version: 18
          
    runs-on: ${{matrix.os-type}}

    steps:
    - name: Checkout action
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.nodejs-version}}

    # - run: npm ci
    - name: Install Dependencies
      run: npm install
    
    - name: Unit testing
      id: mocha-test
      run: npm test
    
    - name: Upload test results to Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with: 
        name: ${{matrix.os-type}}-${{matrix.nodejs-version}}-mocha-test-result
        path: test-results.xml

  code-coverage:
          
    runs-on: ubuntu-latest

    steps:
    - name: Checkout action
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # - run: npm ci
    - name: Install Dependencies
      run: npm install
    
    - name: Unit testing
      continue-on-error: true
      run: npm run coverage
    
    - name: Upload test results to Artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: code-coverage-result
        path: coverage
        retention-days: 5
    
    

