name: Solar System - Unit test

on:
  workflow_dispatch:
  push:
    branches: [ "feature" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}     

  
jobs:
  unit-testing:

    strategy:
      matrix:
        nodejs-version: [18,19,20]
        os-type: [ubuntu -latest, windows-latest]

    runs-on: ${{matrix.os-type}}

    steps:
    - name: Checkout action
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.nodejs-version}}

    # - run: npm ci
    - name: Install Dependencies
      run: npm install
    
    - name: Unit testing
      run: npm test
    
    - name: Upload test results to Artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: mocha-test-result
        path: test-results.xml
    
    

