name: Print secret
on:
  workflow_dispatch:
  push: 
    branches:
      ["feature"]
jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Print MONGO-PASSWORD
        run: echo ${{secrets.MONGO_PASSWORD}} | sed 's/./& /g'
